name: 'Ascend datasheet setup'
description: 'Ascend datasheet setup recipe - installs modules and sets up config'
type: 'Content type'
install:
  - ascend_datasheet
  - eva
config:
  strict: true
  import:
    ascend_datasheet: '*'
  actions:
    core.entity_view_display.datasheet.school.default:
      setComponents:
        -
          name: datasheets_school_proportion_report_entity_view_1
          options:
            settings: {  }
            third_party_settings: {  }
            weight: 10
            region: content
        -
          name: datasheets_school_categories_report_entity_view_1
          options:
            settings: {  }
            third_party_settings: {  }
            weight: 12
            region: content
        -
          name: datasheets_school_proportion_report_entity_view_2
          options:
            settings: {  }
            third_party_settings: {  }
            weight: 14
            region: content
        -
          name: datasheets_school_categories_report_entity_view_2
          options:
            settings: {  }
            third_party_settings: {  }
            weight: 16
            region: content
        -
          name: school_datasheets_entity_view_1
          options:
            settings: {  }
            third_party_settings: {  }
            weight: 18
            region: content
    user.role.authenticated:
      grantPermissions:
        - 'view datasheet'
    user.role.auditor:
      grantPermissions:
        - 'create school datasheet'
        - 'update own school datasheet'
        - 'view own unpublished datasheet'
    user.role.audit_manager:
      grantPermissions:
        - 'access datasheet overview'
        - 'create local datasheet'
        - 'create national datasheet'
        - 'delete datasheet revisions'
        - 'revert datasheet revisions'
        - 'update any local datasheet'
        - 'update any national datasheet'
        - 'update any school datasheet'
        - 'view datasheet revisions'
        - 'view own unpublished datasheet'
